version: '3'

services:
  db:
    image: rethinkdb
    restart: always
    ports:
      - "8002:28015"
      - "8003:8080"
    volumes:
      - ./var/rethinkdb:/data
  webapp:
    image: teammark-web
    build:
      context: .
      dockerfile: ./Dockerfile-webapp
    volumes:
      - ./src:/app
    ports:
      - "8000:8080"
    links:
      - db
  backend:
    image: teammark-backend
    build:
      context: .
      dockerfile: ./Dockerfile-backend
    volumes:
     - ./src:/app
    ports:
      - "8001:9090"
    links:
      - db